### ISSUE TITLE
Refactorinng : Merge customer/tenant : keep tenant

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#100]
tenant : empty object / not displayed 
+cu  : depreciated

```
tn1
  |_  dc1
        |_....
             |_ rack5 <- tn = tn2
tn2
tn3
```

**Comment by Cedrok** [comment]
Done in commit 7634b278abaefba870d0251f1263ab603ba199e8
`+cu:[name]@[color]` and `+tn:[name]@[color]` commands triggers the same Tenant creation.
