### ISSUE TITLE
Tenant Site (formerly DataCenter)

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#102]
(command)datacenter -> (command)site

+dc => +si

string | address
string | zipcode
string | city
string | country
Vector3 | gps
string | usableColor
string | reservecColor
string | technicalColor

**Comment by Cedrok** [comment]
Done in commit 42463b46d6f0820f8986438a0e97c3ef9f645246
`+datacenter:[name]@[orientation]` becomes `+site:[name]@[orientation]`
`+dc:[name]@[orientation]` becomes `+si:[name]@[orientation]`
