### ISSUE TITLE
Object description is "multiline"

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#104]
Step 1 : 

DEMO.ALPHA.B.R1.porthos.description=HPC Porthos
DEMO.ALPHA.B.R1.porthos.description2=17500 cpu / 42 TB Memory
DEMO.ALPHA.B.R1.porthos.descriptionN=150 kW

Step2 (future issue)
DEMO.ALPHA.B.R1.porthos.descriptionN.fontsize=12
DEMO.ALPHA.B.R1.porthos.description1.fontsize=25
DEMO.ALPHA.B.R1.porthos.description1.color=#ff0000

or 

DEMO.ALPHA.B.R1.porthos.description=[ "HPC Porthos", "17500 cpu / 42 TB Memory", "150 kW"]
(less dynamic if we want to change/ update only description2)
(separate color / font / fontsize : not possible) 

==> forget

**Comment by Cedrok** [comment]
Step one done in commit 2a25d2c83de491e375248567e7f88487ca311824
`[name].descriptionX=[value]` where X is the index to set or modify the description

**Comment by Cedrok** [comment]
Stop two done in commit 949dacecdf099faa765c69e9655bb69f6d054144
- bold
- italic
- color
