### ISSUE TITLE
alpha is not restored when existing "focus mode"

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#109]
// AthosCorridor
+co:EDF.NOE.BI2.C8.AthosCorridor@{A03,B15}@cold
EDF.NOE.BI2.C8.AthosCorridor.alpha=50

![image](https://user-images.githubusercontent.com/61938544/107412083-8e3d5e00-6b0f-11eb-9631-1171b6957b24.png)
double clic ...
![image](https://user-images.githubusercontent.com/61938544/107412109-95fd0280-6b0f-11eb-8044-cb42b4bcd433.png)
double clic ...
![image](https://user-images.githubusercontent.com/61938544/107412130-9d241080-6b0f-11eb-87b2-2fd65ebfe02d.png)

**Comment by Cedrok** [comment]
Fixed in commit 0f552eb
