### ISSUE TITLE
Room orientation : need SW

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#120]
Need SW at least (thus every combinaison) to ba able to represent UC2 room

\(UC2 est en dessous de UC1 si tu devais mettre les plans bout a bout\)

**Comment by Cedrok** [comment]
Done in commit 6adea6dbdaead758e682da0be8a0484944e21eb2
When creating a room, we now need to add "+/-" to the orientation: **+E+N instead of EN**. This allow us to choose the "starting corner" for populating the racks.
