### ISSUE TITLE
new command : devicegroup

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#121]
like rackgroup but for devices

a device group may be accross racks, 
same method : bounding box / children objects are hidden

**Comment by Cedrok** [comment]
Devicegroup and Rackgroup merged in a single Group object 
```
+group:[name]@{c1,c1,...,cN}
+gr:[name]@{c1,c1,...,cN}
```
In commit d657f221f479d6ec8c51550df2e8bc64ba01a81d
