### ISSUE TITLE
UNITY bug: RACKGROUP : odd number of rack

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#125]
`+rackgroup:D.S.B.R.BuGiga@{P01,P02,P03,P04,P05,Q01,Q02,Q03,Q04}`

![image](https://user-images.githubusercontent.com/61938544/110754804-8117aa00-8248-11eb-9fa8-1805aebd1455.png)

P05 not included ...

**Comment by Cedrok** [comment]
Fixed in commit ef2bebaffabdf0679bda03c8906f6977db621b9c
