### ISSUE TITLE
rack tile in "info" does not reflect rack position

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#126]
+rk:D.S.B.R.A13@[16,0]@[80,120,42]@front
+rk:D.S.B.R.A23@[30,0]@[80,120,42]@front
![image](https://user-images.githubusercontent.com/61938544/111026033-67ad6400-83e8-11eb-83e1-b15a6d92642c.png)

**Comment by hchybz** [comment]
rack height is not correct when a rack defined with template

![image](https://user-images.githubusercontent.com/61938544/111536352-6ffbfb00-876a-11eb-8616-5321558a6ea2.png)

but ok when no template
![image](https://user-images.githubusercontent.com/61938544/111536384-78543600-876a-11eb-9683-104649653f49.png)

**Comment by Cedrok** [comment]
Height bug fixed in commit 2d98bc4ed8c6457304ef78ad40815ac6e5d98682
