### ISSUE TITLE
rack aligned "centered" when front/rear (room in +S-E)

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#127]
![image](https://user-images.githubusercontent.com/61938544/111026248-95df7380-83e9-11eb-98b4-47365524f0d3.png)

```
+rk:C.S.B.R.K01@[0,39]@[61,100,40]@rear
+rk:C.S.B.R.K02@[1.01666666666667,39]@[61,100,40]@rear
+rk:C.S.B.R.K04@[2.03333333333333,39]@[60,120,42]@rear
+rk:C.S.B.R.L01@[0,43]@[60,120,42]@front
+rk:C.S.B.R.L02@[1,43]@[61,100,40]@front
+rk:C.S.B.R.L02_OL@[2.01666666666667,43]@[60,120,42]@front

```

![image](https://user-images.githubusercontent.com/61938544/111026323-f5d61a00-83e9-11eb-8e77-30d3fa30b32a.png)

You cheated somewhere.. it is ok when room is +X+Y

**Comment by Cedrok** [comment]
Fixed in commit 7400a02
