### ISSUE TITLE
Outline / select several objects in scene

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#149]
Given a set of objects, not necessarly of same type,
"highlight" them or their parents

CED.SITEA.B1.R1.Rack1.Chassis1.Blade1.Eth1
CED.SITEA.B1.R1.Rack1.Swich12.Port12
CED.SITEA.B1.R1.Rack2.Server3.Eth2
CED.SITEA.B1.R2.Rack2.Server4.Eth1
CED.SITEA.B1.R2.Rack2.PDU1.Outlet24

Will be the first step of "highlighting" objects linked by a cable / a VLAN / ...

Computes bounding box of all objects, center scene to display all objects

**Comment by Cedrok** [comment]
New highlight command using hierarchyName
If given object is hidden, its parent will be highlighted (up to rack)
