### ISSUE TITLE
Comments // could begin anywhere in line + doc in Wiki

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#152]
+rk:DEMO.ALPHA.A.R0.iDPx@[5,5]@ibm-idpx-7825-1rx@front
  //  DEMO.ALPHA.A.R0.iDPx.alpha=true
    DEMO.ALPHA.A.R0.iDPx.slots=true

Comment is in error since line is not starting with comment

=> wipe all chars after //

+ add a comment section in wiki  with 2 examples

**Comment by Cedrok** [comment]
Done in commit 8fdb74152056f27eac37f70e45826af1c9dc3910

**Comment by Cedrok** [comment]
Doc here: https://github.com/ditrit/OGREE-3D/wiki/CLI-langage#Comments
