### ISSUE TITLE
manage flipped PCI adapters in servers

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#153]
PCI adapters can be placed in 3 ways in server

- vertically
- horizontally front top
- horizontally back top

horizontal adapters could be with pci connector on right or left

on REAR of server , +X is right to left <-----+x--------

if adapter is smaller (width) than slot, it will be stacked on right of slot.
if adapter is "back top" => adapter should be stacked on left of slot

2 solutions : 
- add another "side" verb for device, "upsidedown" or "flipped"
- add option for slot in JSON model
- 
![image](https://user-images.githubusercontent.com/61938544/126874969-15f81b6d-792d-43bd-9cc9-50fdc2ac1461.png)
![image](https://user-images.githubusercontent.com/61938544/126874981-3f18189b-7b11-4ed1-a730-2fb81c156771.png)

Doc is here D:\Nextcloud.ditrit\Ogree\5_Misc\adapter_front_back_top.docx

**Comment by Novanef** [comment]
Waiting for [CLI issue #121](https://github.com/ditrit/OGrEE-CLI/issues/121)
