### ISSUE TITLE
create component = { +dv + dv + dv +dv ... }

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#154]
+cp = {  rootname=#porthos_cn
+dv : server
+dv  : processor into slot #cpu1
+dv : dimm1 .. + dv: dimm8 into slot #dimm8
+dv: adapter1 into slot #slot1
+dv: disk1 into slot #disk1
}

+dv=DOMAIN.SITE.BUILDING.ROOM.RACK.compute@u02@porthos_cn

like a template
ONLY for DEVICES
Possible to allow only with json, like template

**Comment by Cedrok** [comment]
CLI is now out of the 3D client
