### ISSUE TITLE
Add pillar in room

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#159]
+pillar:[name]@[pos]@[size]

height of pillar = height of room
size = vector2 : pillar base = rectangle / square
size = int : pillar base = circle

**Comment by hchybz** [comment]
move to room attribute instead of a new category of object

like separator

**Comment by Novanef** [comment]
Waiting for [CLI issue #121](https://github.com/ditrit/OGrEE-CLI/issues/121)
