### ISSUE TITLE
Object / Attribute separator change from "." to ":"

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#173]
replace ".attr"

+group:EDF.NOE.BI2.C8.LANcore@{B03b,C03b}
EDF.NOE.BI2.C8.LANcore.description1=LAN Core
EDF.NOE.BI2.C8.LANcore.description2=2 x N7K 10 slots
EDF.NOE.BI2.C8.LANcore.label=#description
EDF.NOE.BI2.C8.LANcore.domain=exaion_lan

by ":attr"

+group:EDF.NOE.BI2.C8.LANcore@{B03b,C03b}
EDF.NOE.BI2.C8.LANcore:description1=LAN Core
EDF.NOE.BI2.C8.LANcore:description2=2 x N7K 10 slots
EDF.NOE.BI2.C8.LANcore:label=#description
EDF.NOE.BI2.C8.LANcore:domain=exaion_lanv

**Comment by Cedrok** [comment]
Done in commit 8cd7ef0bda2808def0532edf50df6a73cfbd38d8 & wiki updated
