### ISSUE TITLE
attribute label could be a list of mixed attributes 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#179]
FOOBAR.Site.CTN.R1.RF:label=#description,#weight,#attribute1,...#attributeN

group | corridor | rack | device

**Comment by hchybz** [comment]
possible to implement this like that ? 

1/ concat 2 attributes into a variable
2/ assign an object's attribute with a variable value ?

.var:ME="FOOBAR.Site.CTN.R1.RF:description" + "FOOBAR.Site.CTN.R1.RF:weight"
FOOBAR.Site.CTN.R1.RF:label=$ME

**Comment by Novanef** [comment]
Waiting for [CLI issue #117](https://github.com/ditrit/OGrEE-CLI/issues/117)
