### ISSUE TITLE
Add new gesture mode like "OpenScad"

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#19]
Native UNITY gesture is more "game engine" than "CAD software"

Need 2/3 options : 
- native UNITY gesture ("AntMan mode")
- CAD oriented gesture ("Sketchup/OpenScad mode")
- "Human Mode" : fixed height , camera is only translated in X/Y at fixed height

**Comment by Cedrok** [comment]
2 modes: Human & Free
Done in commit 4bb2d3b80f357978f2b7de4310e6ace94ffd58f3
