### ISSUE TITLE
REQ00 : compile for MacOS

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-3D#2]

**Comment by Cedrok** [comment]
Done in release v2.2 (https://github.com/ditrit/OGREE-3D/releases/tag/v2.2)

**Comment by hchybz** [comment]
have pb to open on catalina 10.15.7

**Comment by hchybz** [comment]
![Capture d’écran 2021-07-27 à 16 09 42](https://user-images.githubusercontent.com/61938544/127168912-084db131-a2df-4155-83ef-4b3176f97819.png)
