### ISSUE TITLE
Add Chassis/Devices/Subdevices

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#20]
Like SITE/DATACENTER/BUILDING/ROOM

Add new objects : CHASSIS/ DEVICES / COMPONENTS

**Comment by Cedrok** [comment]
Done in commit 57158f20d19396b190575811e3fbd5d9fc3f957b

For Chassis:
```
+device:[name]@[posU]@[sizeU]
+device:[name]@[posU]@[template]
+device:[name]@[slot]@[sizeU]
+device:[name]@[slot]@[template]
```

For all Devices:
```
+device:[name]@[slot]@[template]
```

Loading a device template:
```
.template:device@[path]
```
