### ISSUE TITLE
Room / Building Height : should reflect definition : @[52.5,50,2]

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#24]
for building / room objects

Add a checkbox/toggle : "room walls"

if height is null in size vector : no wall displayed : [52.5,50,0] / [21,42,0]
+bd:/DEMO.ALPHA.BA1@[52,175,0]@[52.5,50,0]
+ro:/DEMO.ALPHA.BI2.C8@[0,10.5,0]@[21,42,0]@SE

if height is specified, wall must has specified height (thickness not taken into account) 

+bd:/DEMO.ALPHA.BA1@[52,175,0]@[52.5,50,5]
+ro:/DEMO.ALPHA.BI2.C8@[0,10.5,0]@[21,42,4]@SE

**Comment by Cedrok** [comment]
Done in commit e627fcf9292679e8ca9d375edb1be7f8552a4449
