### ISSUE TITLE
some room walls are missing 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#25]
South walls are always missing

all 4 walls should be displayed.. event if some walls are ovelapping each other for adjacent rooms
![image](https://user-images.githubusercontent.com/61938544/90289023-477dec80-de7b-11ea-87a1-cf0b18db18a5.png)

**Comment by Cedrok** [comment]
Walls are planes, should be boxes

**Comment by Cedrok** [comment]
Fixed in commit e627fcf9292679e8ca9d375edb1be7f8552a4449
