### ISSUE TITLE
Camera as "human" standing in room

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#26]
Add option (button?)

- Camera is like "human eyes" ( at a fixed height from ground (1.80m))
- fixing point at same height (horizontal) is displayed

- Add CTRL (or another key) + LEFT / RIGHT : to rotate camera like a human would rotate his head left/right
- Add CTRL + UP/DOWN : to rotate head from bottom / top
- Add a "pointing" something to see where camera (eyes) is(are) pointing /looking

So in "human mode" : 

- LEFT/RIGHT/TOP/BOTTOM : move in room in X/Y
- CTRL + L/R/T/B : rotate head /camera
- something is displayed to see where camera/eye is pointing

(could be in v2)

**Comment by Cedrok** [comment]
## Free mode movement 
- Right click + drag: rotate camera
- Middle click + drag: move camera on X & Z local axis
- Scroll wheel: move camera on Y local axis
- zsqd / arrow keys: move camera on X & Y local axis 
- Left shift + zsqd / arrow keys: rotate camera

## Human mode movement
- Right click + drag: rotate camera
- zsqd / arrow keys: move camera on X & Y axis 
- Left shift + zsqd / arrow keys: rotate camera

Done in commit 4bb2d3b80f357978f2b7de4310e6ace94ffd58f3
