### ISSUE TITLE
+building with orientation Negative 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#263]
- wants "-W+N" for building
- same as rooms

**Comment by Novanef** [comment]
Waiting for [CLI issue #116](https://github.com/ditrit/OGrEE-CLI/issues/116)

**Comment by Cedrok** [comment]
New orientation done in commit d74c135
New documentation : https://github.com/ditrit/OGrEE-CLI/wiki/CLI-language#Create-a-Building
