### ISSUE TITLE
Add "separator" in room : wire wall

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#27]
+separator:/CUST.DATACENTER.BUILDING.ROOM.name@[x,y,0]@[width,0,height]

Wire wall to separate zones  in a room

should be discussed : wire wall could be an option for +zones

**Comment by Cedrok** [comment]
```
+separator:[name]@[pos1]@[pos2]
+sp:[name]@[pos1]@[pos2]
``` 
Done in commit 4128187f1aa6340c0b2875156c6df8a0e19507c2
