### ISSUE TITLE
rack : posZ <> 0

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#274]
for cable tree
for wall racks

posZ should be set to something <> 0

- [x] Handle posXYZ attribute for a rack
- [x] Update wiki

**Comment by Novanef** [comment]
Waiting for [CLI issue #122](https://github.com/ditrit/OGrEE-CLI/issues/122)

**Comment by Cedrok** [comment]
Dev done in commit 46ae1b0
