### ISSUE TITLE
Room names oriented as site

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#28]
Room names should be oriented in the "red axis" geometric referential (site)

not in the green one (room/racks)

"couloirinterne" : OK
"C[1-8]" : KO : flip 180°

names in +X or +Y

**Comment by Cedrok** [comment]
Not a bug, to be documented: room name is always in room geometric referential

**Comment by Cedrok** [comment]
Done in commit 0c2fa93412420e5beca8724950f64391db7b801d
