### ISSUE TITLE
Review sensors

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-3D#308]
- [x] Create a DEMO.SENSORS ocli file
- [x] Duplicated code between CliParser.ModifyObject() & Object.UpdateFromSApiObject()
- [x] Create a new sensor doesn't always trigger the sensor creation in the 3D client -> sensor can not be created anymore
- [x] Update a "temperature_x" sensor 
- [x] Fix slots & components' renderers being active when they shouldn't
- [x] Basic sensors on racks aren't displayed ->feature

**Comment by Novanef** [comment]
Added renderer issue

**Comment by Novanef** [comment]
Added basic sensor issue
