### ISSUE TITLE
Rack pos + label not correct when orientation is "right"

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#31]
When rack orientation is "right" 

- label is not on face : small distance between label and face
![image](https://user-images.githubusercontent.com/61938544/90320572-b70adf00-df42-11ea-9226-75c62ed0955d.png)
- rack pos is not good when orientation is right (and left?)
![image](https://user-images.githubusercontent.com/61938544/90320735-f685fb00-df43-11ea-9e26-6a60c01cd24f.png)

**Comment by Cedrok** [comment]
Fix placement in commit 971f2eb3a688d4718dac1c642d2c3f1ba92cd951

**Comment by Cedrok** [comment]
Fix label position in commit f99264e7ea0fd6fc1649de2a38dc4d91f0c0ebca
