### ISSUE TITLE
Select object(s) with mouse and change context in CLI windows

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#34]
After loading my <main>.ocli... all is displayed
<scope> in CLI prompt is "EDF.NOE"

want to select NOE.EDF.BI2.C8.J12 by simply click on J12 rack

(in v2, when rack is selected, devices will be displayed... devices should be selectable also)..

=> reflexion about a multiple selection to change / set properties

![image](https://user-images.githubusercontent.com/61938544/90803053-76331180-e318-11ea-8b51-6af085a0d1f2.png)

==> idea is to be able to move objects/group of objects with mouse

**Comment by Cedrok** [comment]
Single click selection done in commit 4b36c743dae5e9c675d23a6c67fb260ae1506d59
Multi click selection (Left Control + click) done in commit 69909ddd956e79092c93aa459bae4cee4286b14a
Move single rack done in commit d20d6db332aaf46ae692dd29cc600b76fc187a65

**Comment by Cedrok** [comment]
Move multiple racks done in commit b315f63a870f768e990e422437834a2c33b55b15
