### ISSUE TITLE
Add VARIABLE in OCLI files

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#37]
.cmds:C:\Users\herve\Nextcloud.ditrit\Ogree\4_customers\__EDF__\EDF.NOE.ocli
.template:rack@/home/cedrok/_Orness/CmdsOgree3D/ibm-rack.json

replaced by 

+var:CUST@"C:\Users\herve\Nextcloud.ditrit\Ogree\4_customers\__EDF__\"
+var:TEMPLATE@/home/cedrok/_Orness/CmdsOgree3D/

.cmds:$CUST\EDF.NOE.ocli
.template:rack@$TEMPLATE/ibm-rack.json

**Comment by Cedrok** [comment]
Done in commit 3318d15d8d8278e1882e2219452cec4b7bcb0f38
Example:
```
.var:CUST=C:\Users\herve\Nextcloud.ditrit\Ogree\4_customers_EDF_
.cmds:${CUST}\EDF.NOE.ocli
```
