### ISSUE TITLE
Add "U location" at each corner of a rack to simply identify objects

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#39]
Add an attribute like ".displayU = true" on rack object 
to display something like this 

![image](https://user-images.githubusercontent.com/61938544/91060634-7ccccc00-e62b-11ea-98f4-9a579df275b9.png)
![image](https://user-images.githubusercontent.com/61938544/91060695-8eae6f00-e62b-11ea-9c7a-7452c59aa4b4.png)

label on "external faces" (thus different at each corner)

**Comment by Cedrok** [comment]
`rack.displayU=[true|false]`
done in commit 0c5846a09c620140a12850c329c1e03e020dc955
