### ISSUE TITLE
Add tile "names layout" (calepinage) below name numbers (11/48)

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#43]
tile numbers are computed for the double X/Y loop during display

2 cases :
- all rooms are based on the same tile template (NOE) : 1 simple template for all room
- 1 template per room / mapping betwwen tile name and tile number can not be "computed" (PACY)

Thus : 
- template with tile number and names
- stored in DB
- loaded as a JSON from DB / from file when OgrEE starts

**Comment by Cedrok** [comment]
One template per room:
tiles in commit ded167f2cb68e562e418ead5afb20630d499a9c0
separators in commit 4128187f1aa6340c0b2875156c6df8a0e19507c2

**Comment by Cedrok** [comment]
"aisles" will be dealt in a later issue
