### ISSUE TITLE
Parser : wipe all space before start parsing

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#44]
wipe all spaces in command line before starting parsing

regarding size of definition file, customer may want to align command with a rectangular editor.. 

![image](https://user-images.githubusercontent.com/61938544/91655577-e6c4f580-eab1-11ea-9ad9-0114437eca6a.png)
![image](https://user-images.githubusercontent.com/61938544/91655589-fba18900-eab1-11ea-97ab-c121d399eb74.png)

want to be able to handle that :-)

![image](https://user-images.githubusercontent.com/61938544/91655658-723e8680-eab2-11ea-9a1d-05fe2d7b28cc.png)

(all my perl regexp are starting with 
![image](https://user-images.githubusercontent.com/61938544/91655686-bd589980-eab2-11ea-8e91-faf534b83818.png))

**Comment by Cedrok** [comment]
Fixed in commit b8a4d907eb41a66f98cf6582f7051612b641a746
