### ISSUE TITLE
Wrong position for item rear placed in a slot

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-3D#450]
Placed as front (viewed from the rear):
![image](https://github.com/ditrit/OGrEE-3D/assets/61938544/b8427c77-1c07-4862-932b-72cf47f7f032)

Placed as rear :
![image](https://github.com/ditrit/OGrEE-3D/assets/61938544/73a9750e-f0d7-432c-b0a0-133b1306e4f4)

This is due to the pivot change, the object is not rotated on its center so its position changes

**Comment by Cedrok** [comment]
This is not realy a bug: in this example, slots of the chassis (mellanox-sx6536) don't have their "elemOrient" attribute filled. So the engine interprets the slot as a vertical slot.
The json schema should force the elemOrient field to be filled for a slot
