### ISSUE TITLE
Add tile color as an option (whole DC)

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#47]
when camera is far from scene, colors used for technical / reserved zones can not be distinguished easily

Add a "color" option

for whole <dc>, something like that :

DEMO.ALPHA.rooms.technical@ff3344
DEMO.ALPHA.rooms.reserved@112233

like #43  
DEMO.ALPHA.rooms.tiles = numbers / names / both

**Comment by Cedrok** [comment]
Done in commit 8838c3aaeb946ec7a554121bc3d5fa47299410f9
```
<Datacenter>.usableColor=<hex>
<Datacenter>.reservedColor=<hex>
<Datacenter>.technicalColor=<hex>
```
