### ISSUE TITLE
Do not allow one rack/device to overlay another

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#48]
When an object is moved, verify if destination is not already occupied by another one

(same verification when a device will be moved in the same rack (change U/ change side)

Move could be free if until mouse button is pressed.
When button is released, rack/device position should be checked 
- ok : rack is drawn to new location
- ko : something (visual effect, blink, a forbidden sign) is displayed

**Comment by Cedrok** [comment]
Fixed in commit 191891fc7ad65b37825d9192898fbf1e61760af9
