### ISSUE TITLE
Add "ALT" key + arrows to move camera position/angle 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#49]
Human mode :  camera is positionned à 1.8m from floor / camera angle may vary
- left / right / up / down  :no change
- alt + left/right/ up /down : rotate camera like a human head 
 * left / right : look left / right
* up / down : look ceiling / floor

AntMan mode : camera altitude can be changed / camera angle is fixed (0)

* up / down : move up and down (do not allow to move under the floor (may change in a future release)

**Comment by Cedrok** [comment]
## Free mode movement 
- Right click + drag: rotate camera
- Middle click + drag: move camera on X & Z local axis
- Scroll wheel: move camera on Y local axis
- zsqd / arrow keys: move camera on X & Y local axis 
- Left shift + zsqd / arrow keys: rotate camera

## Human mode movement
- Right click + drag: rotate camera
- zsqd / arrow keys: move camera on X & Y axis 
- Left shift + zsqd / arrow keys: rotate camera

Done in commit 4bb2d3b80f357978f2b7de4310e6ace94ffd58f3
