### ISSUE TITLE
Filename (template / command ) can NOT contain "@" : (special character)

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#53]
since "@" is a separator in OGrEE,  files loaded could not contain "@" in their names .. 

Else they won"t be loaded

![image](https://user-images.githubusercontent.com/61938544/92285186-fd30de00-ef03-11ea-82fa-13559e2c280e.png)

**Comment by Cedrok** [comment]
Allow '@' for template name. Update all regex' patterns.
Done in commit 7413b3ebae2ae8848202aed374ec95c746dfb98c
