### ISSUE TITLE
Room definition from JSON file

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#57]
Replace : 
    //+ro:/EDF.NOE.BI1.C2@[42,52.5,0]@[21,39,0]@SE
    //+zones:/EDF.NOE.BI1.C2@[3,5,3,2]@[0,0,5,5]
+ Add tile names/colors (#43 )

By : 

    //.template:room@/filepath.json
    //+room:/EDF.NOE.BI2.C8@[x,y,z]@slug

Example :

    //.template:room@/C:\Users\herve\Nextcloud.ditrit\Ogree\4_customers\__EDF__\EDF.NOE.evenroom.json
    //+room:/EDF.NOE.BI2.C8@[42,52.5,0]@edf.noe.evenroom

**Comment by Cedrok** [comment]
Done in commit 9ac3eb24bdb0c1503d52784d12d3d292d88bd955
