### ISSUE TITLE
Console history does not keep all commands when files are nested + more lines 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#59]
When OCLI files are nested, only last file commands seems to be kept in history console windows.

Not all lines are displayed

=> check 

+ increase buffer for more lines (should be a parameter of OGrEE)

**Comment by hchybz** [comment]
+ file_name  + line_number when #warning / #error

+ stats [lines / war / err]

**Comment by Cedrok** [comment]
Increase CLI buffer: 500 lines
Done in commit 1eb8274e1d519c337ac13a65ab81ab1d548cdf78
