### ISSUE TITLE
Rack heightU should NOT be computed from heightmm

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#64]
a 47U rack is 2200 mm in height 

2200/44.45 = 49.49U

in +rack:....@[600,1200,47] : easy : 47
in json template, should use :

"sizeWDHmm"  : [800 ,1200 ,2200],
"sizeWDU"  : [800 ,1200 ,47],

or 

"height" : 47
"heightUnit" : "U" | "OU"

**Comment by Cedrok** [comment]
Rack height from mm value for template, from U value for basics.
In rack template: rack.height is computed from horizontal components.
Done in commit 67bc9c886c9fed0871a8d017e22b8aa6d9aaa721
