### ISSUE TITLE
Add command to move camera in CLI

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#68]
Add a command to move (teleport) / translate (smooth move) camera to a specific position / angle

=camera.move@[x,y,z]@[angleX,angleZ]
=camera.translate@[x,y,z]@angle

=camera.move@[-102.87,1.92,11.08]@[22,90]

**Comment by Cedrok** [comment]
Done in commit 3e4039a3a1db097ae5762180a2d416468289d3e7
```
camera.move@[position]@[rotation]
camera.translation@[position]@[rotation]
camera.wait@[time]
```
