### ISSUE TITLE
tiles are starting from wrong corner (opposite) 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#79]
if room size is not a tile multiple, tile are not drawn correctly

![image](https://user-images.githubusercontent.com/61938544/96702427-05e55280-1392-11eb-9bc4-a9cf869f1f71.png)

"plain" tiles should be at located "1,1"

**Comment by Cedrok** [comment]
Fixed in commit f072264d7f3c2562f204c9c9e385ec69140ea7ac
