### ISSUE TITLE
UI controls as CLI commands

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#85]
<xx>.wireframe
<xx>.camera.*
<xx>.delay=
<xx>.infos= true /false
<xx>.debug = true /false

<object>.localCS= true/false
room.tilesName = true/false
room.tilesColors = true/false
room.tiles = true/false  ==> DEPRECIATED !

**Comment by Cedrok** [comment]
In commit 564c11a1e58b19cd119ca61ad592e22f55424083 : 
`<room>.tilesName=[true|false]` 
`<room>.tilesColor=[true|false]`
`<room>.tiles`removed

**Comment by Cedrok** [comment]
In commit 8d1ffa8c3eca37050e456baafd70d4649e453128
`ui.wireframe=[true|false]`
`ui.infos=[true|false]`
`ui.debug=[true|false]`
Change camera commands:
`camera.move=[position]@[rotation]`
`camera.translate=[position]@[rotation]`
`camera.wait=[time]`

In commit 1834fae98372d5455dc1b38282a3aa3c431d6978
`<object>.localCS=[true|false]`

**Comment by Cedrok** [comment]
In commit 3996ccd37e457fc564a038276189debead1601ba
`ui.delay=[time]`
