### ISSUE TITLE
Connect unity with external API server (json)

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#90]
Connect engine to external api server to retrieve object definitions 

1st step : customer/site/buildings/room with fake API
2nd step : use authentication token
3rd step : real api

**Comment by Cedrok** [comment]
1st step done in commit b06acca1381cd579a3932342e83f4991fd200cae
db url given in config file
```
api.get=[request]
api.post=[name] (called in +cu / +dc)
api.put=[name] (called in [cu/dc].[attribute])
```

**Comment by Cedrok** [comment]
Done in commit b2dd590192a53c99e3e421e11ab9bd78c7ac179d
Default API url: https://ogree.chibois.net (given in default config.json). 
The authentication token have to be given either with a new config file or with  `--serverToken` argument. (in commit aa663602316dcd4b65537cf312cfb54144084bc1)
