### ISSUE TITLE
Add Credit/About window

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#92]
6 months / MVP available

time to add " Credits / About" windows somewhere

OGrEE 3D is an OpenSource project by DitRit community
<license ? (à voir avec Xavier>
Author : Herve CHIBOIS (herve.chibois@orness.com) (GITHUB:hchybz)
Main 3D Dev : Cedric VAUTRAIN (cedric.vautrain@orness.com) (GITHUB:Cedrok)
date / build
https://github.com/ditrit/OGREE-3D

un truc du genre ..

**Comment by Cedrok** [comment]
Done in commit 9d59d526329301cd15f5e04910414bbf267d3603
