### ISSUE TITLE
Object description can be object attribute

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#97]
={F17,F18,F19,F20}
selection.description=HITACHI G1K/F5K

should be completed with

_.description=#bios
_.description=#<object.attribute>

**Comment by Cedrok** [comment]
Done in commit 846992d28fdf88a62430ff10f1c3ce3b0751b4ee
```
[rack|device|rackgroup].label=[attribute]
```
For displaying description:
- Display all lines: `[obj].label=description`
- Display a specific line: `[obj].label=descriptionX` where X is the wanted line
