### ISSUE TITLE
refactoring : replace EObjFamily by [string]Category

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGREE-3D#99]
- needed to merge all objects in a single type
- strings that will be verified with JSON schema will be drawn/displayed as 3D objects
- strings that won't exist in JSON schema will NOT be drawn (teapot / car)

customer | tenant | datacenter | building | room | zone/area | object | rack | rackgroup |  airconditionner / powerpanel | component | pdu | device ... 

to be completed/modified

**Comment by Cedrok** [comment]
<Tenant>tenant replaced by <string>domain in 46a1bf6909fcb0726d915ba2379f3056c72c7759

**Comment by Cedrok** [comment]
Unify all object generators in 109e1caffb4d389b12bf3b7fe91f06acb2969cf5
